name: Minimal CML Report

on:
  push:
    branches: [master, main, week8, w8]
  pull_request:
    branches: [master, main, week8]

permissions:
  contents: write
  pull-requests: write

jobs:
  train_and_report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - uses: iterative/setup-cml@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run training
        run: |
          python train.py

      - name: Generate plot
        run: |
          python plot_metrics.py

      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "# Iris Model Report" > report.md
          echo "## Metrics Table" >> report.md
          cat metrics.csv >> report.md
          echo "## Metrics Plot" >> report.md
          echo "![Metrics](metrics_plot.png)" >> report.md
          cml comment create --publish report.md

