name: Train and Report

on:
  push:
    branches: [master, main, week8]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc[gcs] cml

      - name: Set up GCP credentials
        env:
          GCP_KEY_JSON: ${{ secrets.GCP_KEY_JSON }}
        run: |
          echo "$GCP_KEY_JSON" > key.json
          export GOOGLE_APPLICATION_CREDENTIALS=key.json
          dvc remote modify gcsremote credentialpath key.json

      - name: Pull data with DVC
        run: dvc pull

      - name: Train model
        run: |
          python train.py

      - name: Generate report
        run: |
          echo "# Training Report" > report.md
          cat metrics.csv >> report.md
          echo "![Metrics](metrics_plot.png)" >> report.md

      - name: Comment report on PR
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment create report.md

