name: Iris Model Training

on:
  workflow_dispatch:
  push:
    branches: [main, master, week8]
  pull_request:
    branches: [main, master, week8]

permissions:
  contents: write
  pull-requests: write

jobs:
  train_model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training
        run: |
          python train.py > train_output.txt 2>&1

      - name: Set up CML
        uses: iterative/setup-cml@v2

      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## 🚀 Training Output" >> report.md
          echo "\`\`\`" >> report.md
          cat train_output.txt >> report.md
          echo "\`\`\`" >> report.md

          echo "## 📊 Training Metrics" >> report.md
          echo "\`\`\`csv" >> report.md
          cat metrics.csv >> report.md
          echo "\`\`\`" >> report.md

          cml comment create --publish report.md

