name: Iris CML Report

on:
  workflow_dispatch:
  push:
    branches: [main, master, week8]
  pull_request:
    branches: [main, master, week8]

permissions:
  contents: write
  pull-requests: write

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run training
        run: python train.py

      - uses: iterative/setup-cml@v2

      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## 📊 Metrics" > report.md
          echo "\`\`\`csv" >> report.md
          cat metrics.csv >> report.md
          echo "\`\`\`" >> report.md
          echo "[View raw report file](./report.md)" >> report.md
          cml comment create --publish report.md

